$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
$componentRoot = Join-Path $projectRoot 'work/components'
$outputPath = Join-Path $projectRoot 'src/animation_data.rs'

$sheets = @(
    @{ File = 'dee_jay.csv'; Constant = 'DEE_JAY_COMPONENTS'; Character = 'DeeJay' },
    @{ File = 'rose.csv'; Constant = 'ROSE_COMPONENTS'; Character = 'Rose' },
    @{ File = 'fei_long.csv'; Constant = 'FEI_LONG_COMPONENTS'; Character = 'FeiLong' },
    @{ File = 'cammy.csv'; Constant = 'CAMMY_COMPONENTS'; Character = 'Cammy' }
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by tools/generate_animation_data.ps1 from the audited sprite components.')
$lines.Add('use super::{Character, SpriteFrame};')
$lines.Add('')

foreach ($sheet in $sheets) {
    $rows = @(Import-Csv (Join-Path $componentRoot $sheet.File) | Sort-Object { [int]$_.index })
    $lines.Add("pub(super) const $($sheet.Constant): [SpriteFrame; $($rows.Count)] = [")
    foreach ($row in $rows) {
        $lines.Add("    SpriteFrame::new($($row.x).0, $($row.y).0, $($row.w).0, $($row.h).0),")
    }
    $lines.Add('];')
    $lines.Add('')
}

$lines.Add('pub(super) fn component_frame(character: Character, index: u16) -> SpriteFrame {')
$lines.Add('    match character {')
$lines.Add('        Character::DeeJay => DEE_JAY_COMPONENTS[index as usize],')
$lines.Add('        Character::Rose => ROSE_COMPONENTS[index as usize],')
$lines.Add('        Character::FeiLong => FEI_LONG_COMPONENTS[index as usize],')
$lines.Add('        Character::Cammy => CAMMY_COMPONENTS[index as usize],')
$lines.Add('    }')
$lines.Add('}')

[System.IO.File]::WriteAllLines($outputPath, $lines)
Write-Output "Generated $outputPath"
